import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "components/Footer/Footer";
import styles from "styles/Home.module.css";
import { Box } from "grommet";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Organise My Meals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Footer />
    </div>
  );
};

export default Home;
